/* Ultimate Clock · versión y novedades. Cada publicación sube VERSION (igual al número de caché de sw.js)
   y agrega arriba una entrada breve en español e inglés. */
(function (root) {
  'use strict';
  const VERSION = 42;
  const ENTRIES = [
    {version:42,date:'2026-10-03',es:['Se pueden guardar varios torneos: lista Mis torneos, NUEVO TORNEO y cambio entre ellos.','Tabla de posiciones (victoria 3, empate 1) y lista de resultados con los partidos guardados del torneo.','Se pueden eliminar planillas guardadas, con confirmación.','El pase y el gol no pueden ser de la misma persona.','En modo torneo no se puede empezar el reloj ni anotar goles sin elegir los dos equipos de la lista.','Cartel más corto (PARTIDO / TORNEO) y un paso nuevo del tutorial sobre los modos.'],en:['You can keep several tournaments: My tournaments list, NEW TOURNAMENT and switching between them.','Standings table (win 3, draw 1) and a results list from the tournament saved matches.','Saved sheets can be deleted, with confirmation.','The assist and the goal cannot be by the same person.','In tournament mode you cannot start the clock or score goals before picking the two teams from the list.','Shorter badge (MATCH / TOURNAMENT) and a new tutorial step about the modes.']},
    {version:41,date:'2026-10-03',es:['MENU → SALIR DEL MODO TORNEO (y ENTRAR AL MODO TORNEO / EQUIPOS DEL TORNEO según el modo).','En modo partido ahora se pregunta por los jugadores (opcional): se eligen de la lista en el gol y siempre se puede escribir otro nombre.','El modo partido no recuerda nada: cada partido nuevo y cada vez que se abre la app con un partido ya guardado se empieza con equipos en blanco.','＋ NUEVO PARTIDO sigue en el modo actual (en torneo va directo a elegir los dos equipos).'],en:['MENU → EXIT TOURNAMENT MODE (and ENTER TOURNAMENT MODE / TOURNAMENT TEAMS depending on the mode).','Match mode now asks for players (optional): they are picked from the list when a goal is scored, and you can always type another name.','Match mode remembers nothing: every new match, and every time the app opens with an already saved match, starts with blank teams.','＋ NEW MATCH stays in the current mode (in tournament mode it goes straight to picking the two teams).']},
    {version:40,date:'2026-10-03',es:['Al empezar hay dos opciones: MODO PARTIDO y MODO TORNEO. MODO TORNEO lleva directo al creador de equipos.','El encabezado indica si estás en MODO PARTIDO o MODO TORNEO.','En modo torneo los equipos se eligen de la lista y el pase y el gol se eligen de los jugadores cargados (no se escriben).','En modo partido los nombres de equipos, pase y gol se escriben a mano, también desde la planilla.'],en:['At the start there are two options: MATCH MODE and TOURNAMENT MODE. TOURNAMENT MODE goes straight to the team creator.','The header shows whether you are in MATCH MODE or TOURNAMENT MODE.','In tournament mode teams are picked from the list and assist and goal are picked from the loaded players (not typed).','In match mode team, assist and goal names are typed by hand, also from the sheet.']},
    {version:39,date:'2026-10-03',es:['Modo torneo más simple: cada equipo se completa en una ficha con nombre, color y 14 casilleros de jugadores.','AGREGAR JUGADOR suma una fila más; AGREGAR EQUIPO guarda la ficha completa y se pueden cargar tantos equipos como haga falta.','Enter pasa a la fila siguiente; se avisa si falta un nombre o si un número está repetido.'],en:['Simpler tournament mode: each team is filled in on one sheet with name, color and 14 player slots.','ADD PLAYER adds another row; ADD TEAM saves the whole sheet and you can load as many teams as needed.','Enter moves to the next row; you are warned if a name is missing or a number is repeated.']},
    {version:38,date:'2026-10-03',es:['Modo torneo: cargá los equipos y sus jugadores (el número es opcional) desde MENU → MODO TORNEO.','Al empezar un partido elegís los equipos de la lista y, al anotar un gol, elegís quién dio el pase y quién lo hizo.','Estadísticas de goles y pases por jugador, y exportación e importación del torneo en un archivo.'],en:['Tournament mode: load teams and their players (the number is optional) from MENU → TOURNAMENT MODE.','When you start a match you pick teams from the list and, when a goal is scored, you pick who assisted and who scored.','Goal and assist stats per player, and tournament export and import as a file.']},
    {version:37,date:'2026-10-02',es:['El time out ya no pausa el reloj del partido.'],en:['A time out no longer pauses the game clock.']},
    {version:36,date:'2026-10-02',es:['Los botones de Time Out vuelven a funcionar.','El time out detiene el reloj del partido.','El llamado se puede reiniciar mientras corre.'],en:['The Time Out buttons work again.','A time out stops the game clock.','A call can be reset while it runs.']},
    {version:35,date:'2026-10-02',es:['Los perfiles de tiempo guardados se pueden eliminar desde el inicio y desde Editar tiempos.','Los tiempos se cargan en números enteros.','El Pull se puede reiniciar mientras corre.','El llamado arranca al tocarlo y la categoría se elige mientras corre; Stall pasa a llamarse Conteo.','En el menú, CONFIGURAR pasa a EDITAR TIEMPOS.'],en:['Saved time profiles can be deleted from the start screen and from Edit times.','Times are entered as whole numbers.','The pull can be reset while it runs.','A call starts as soon as you tap it and you pick its type while it runs.','In the menu, SETTINGS is now EDIT TIMES.']},
    {version:34,date:'2026-10-02',es:['En el inicio solo se marca el perfil elegido.','Al guardar los tiempos en Configuración se vuelve al tablero.'],en:['Only the chosen profile is highlighted at the start.','Saving times in Settings returns to the board.']},
    {version:33,date:'2026-10-02',es:['El inicio ahora tiene tres pantallas: equipos, perfil de tiempo y tiempos personalizados.','Los tiempos personalizados se guardan como perfil y quedan en la lista.'],en:['The start screen now has three steps: teams, time profile and custom times.','Custom times are saved as a profile and stay in the list.']},
    {version:32,date:'2026-10-02',es:['Corregidos los títulos de equipo en el cuadro de equipos.'],en:['Fixed the team titles in the teams box.']},
    {version:31,date:'2026-10-02',es:['Al anotar un gol se abre el cuadro para escribir quién hizo el gol y el pase.','Cada partido nuevo pide el nombre y el color de los dos equipos.'],en:['Scoring a goal opens a box to type the scorer and the assist.','Every new game asks for both teams’ names and colors.']},
    {version:30,date:'2026-10-02',es:['El pull dura 90 s y avisa con 1, 2 y 3 silbatos a los 45, 60 y 75 s, y con 4 al final.','Marcas de los avisos en la línea del pull.'],en:['The pull lasts 90 s and signals with 1, 2 and 3 whistles at 45, 60 and 75 s, and 4 at the end.','Warning marks on the pull countdown line.']},
    {version:29,date:'2026-10-02',es:['Cada tipo de llamado tiene su emoji en WhatsApp.','En horizontal, Pull y Time Out van bajo el reloj y cada equipo tiene su llamado debajo.','Número de versión y novedades en el pie.'],en:['Each call type has its own emoji in WhatsApp.','In landscape, Pull and Time Out sit under the clock and each team has its call below.','Version number and what’s new in the footer.']},
    {version:28,date:'2026-10-02',es:['Bienvenida al abrir la app y aviso de cómo se guardan los datos.','Enviar la planilla por WhatsApp.'],en:['Welcome screen and a note on how data is stored.','Send the scoresheet by WhatsApp.']},
    {version:27,date:'2026-10-02',es:['«Llamado» en toda la app.'],en:['Consistent wording for calls.']},
    {version:26,date:'2026-10-02',es:['Tarjetas más prolijas en pantallas chicas.'],en:['Tidier cards on small screens.']},
    {version:25,date:'2026-10-02',es:['App en inglés con selector de idioma.'],en:['English version with a language switch.']},
    {version:24,date:'2026-10-02',es:['Mejor vista al compartir el enlace e instalar la app.'],en:['Better previews when sharing the link and installing the app.']},
    {version:23,date:'2026-10-02',es:['Botón para apoyar el proyecto.'],en:['Button to support the project.']},
    {date:'2026-10-02',es:['Tablero nuevo, sin scroll en celular y tablet.','Gol con un toque, pantalla encendida y correcciones.','Exportar planillas en PDF y CSV.'],en:['New board with no scrolling on phone and tablet.','One-tap goals, screen kept on and fixes.','Export scoresheets as PDF and CSV.']},
    {date:'2026-09-30',es:['Perfiles de tiempo, tutorial, pantalla completa y alarmas.'],en:['Time profiles, tutorial, full screen and alarms.']},
    {date:'2026-09-29',es:['Llamados por equipo con categorías y Time Out unificado.'],en:['Per-team calls with categories and a single Time Out.']},
    {date:'2026-09-27',es:['Primera versión: reloj, goles, pull, llamados, time outs y planilla.'],en:['First version: clock, goals, pull, calls, time outs and scoresheet.']}
  ];
  const api={VERSION,ENTRIES};
  if(typeof module!=='undefined')module.exports=api;else root.UCChangelog=api;
})(typeof globalThis!=='undefined'?globalThis:this);
