const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function harness({failPlayback=false}={}){const scheduled=[],played=[],visible=[],handlers={};const document={hidden:false,addEventListener:(name,fn)=>handlers[name]=fn};class Audio {constructor(){this.state='running';this.currentTime=0;this.destination={};}resume(){return Promise.resolve();}createOscillator(){if(failPlayback)throw Error('audio device failed');const frequency={value:0,setValueAtTime(value){this.value=value},linearRampToValueAtTime(){}};const o={type:'',frequency,connect(){return {connect(){}}},start(){played.push(o.frequency.value);},stop(){}};return o;}createGain(){return {gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}}};}}
const context={document,window:{AudioContext:Audio},setTimeout:(fn,delay)=>scheduled.push({fn,delay})};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../alerts.js'),'utf8'),context);return {api:context.ClockAlerts,document,scheduled,played,visible,handlers};}
test('completion sounds the buzzer five times after queued signals',async()=>{const h=harness();await h.api.unlock();h.api.setSound(true);h.api.enqueue('threshold',()=>h.visible.push(1));h.api.enqueue('threshold',()=>h.visible.push(2));h.api.enqueue('complete',()=>h.visible.push(3));assert.deepEqual(h.played,[900]);h.scheduled.shift().fn();assert.deepEqual(h.played,[900,900]);h.scheduled.shift().fn();assert.deepEqual(h.played,[900,900,1120,1120,1120,1120,1120]);assert.deepEqual(h.visible,[1,2,3]);});
test('hidden page defers pending signals until visible',async()=>{const h=harness();await h.api.unlock();h.api.setSound(true);h.document.hidden=true;h.api.enqueue('threshold',()=>h.visible.push(1));assert.deepEqual(h.played,[]);h.document.hidden=false;h.handlers.visibilitychange();assert.deepEqual(h.played,[900]);});
test('sound disabled keeps visual alerts without audio permission',()=>{const h=harness();h.api.setSound(false);h.api.enqueue('complete',()=>h.visible.push(1));assert.deepEqual(h.played,[]);assert.deepEqual(h.visible,[1]);});
test('visual completion never waits for audio permission',()=>{const h=harness();h.api.setSound(true);h.api.enqueue('complete',()=>h.visible.push(1));assert.deepEqual(h.visible,[1]);assert.deepEqual(h.played,[]);});
test('test button signal uses the same five buzzer pulses and respects mute',async()=>{const h=harness();assert.equal(h.api.test(),false);await h.api.unlock();h.api.setSound(true);assert.equal(h.api.ready,true);assert.equal(h.api.test(),true);assert.deepEqual(h.played,[1120,1120,1120,1120,1120]);h.api.setSound(false);assert.equal(h.api.ready,false);assert.equal(h.api.test(),false);assert.deepEqual(h.played,[1120,1120,1120,1120,1120]);});
test('playback failure disables sound and still delivers the visual alert',async()=>{const h=harness({failPlayback:true}),failures=[];await h.api.unlock();h.api.setSound(true);h.api.onAudioFailure=()=>failures.push(1);h.api.enqueue('complete',()=>h.visible.push(1));assert.deepEqual(h.visible,[1]);assert.deepEqual(failures,[1]);assert.equal(h.api.ready,false);assert.equal(h.api.test(),false);});
