const {test}=require('node:test');const assert=require('node:assert/strict');const X=require('../sheet-export.js');
const match=(events=[])=>({id:'match-1',savedAt:'2026-10-01T18:30:00.000Z',ruleset:'wfdf',themeName:'Claro',clock:{elapsed:3725},config:{},teams:[{name:'Ñandúes',color:'#1b47e2',score:2},{name:'Los "Halcones", Córdoba',color:'#f59e0b',score:1}],events});
const sample=()=>match([{type:'goal',at:'2026-10-01T17:00:00.000Z',elapsed:61.2,team:0,scorer:'Ana',assist:'=HYPERLINK("x")'},{type:'timeout',at:'2026-10-01T17:10:00.000Z',elapsed:600,team:1,timer:'timeout'},{type:'incident',at:'2026-10-01T17:20:00.000Z',elapsed:900,label:'Lesión',note:'línea 1\nlínea 2 (leve) \\ nada'}]);
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=false;else cell+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell='';}else if(c==='\r'&&text[i+1]==='\n'){row.push(cell);rows.push(row);row=[];cell='';i++;}else cell+=c;}return rows;}
const latin1=bytes=>Buffer.from(bytes).toString('latin1');

test('CSV has a BOM, a header and one row per event with team names and elapsed time',()=>{const csv=X.toCSV(sample());assert.ok(csv.startsWith('﻿'));const rows=parseCSV(csv.slice(1));assert.equal(rows.length,4);assert.deepEqual(rows[0],['fecha_hora','tiempo_juego','evento','equipo','cronometro','detalle','nota','gol','pase','modo']);assert.deepEqual(rows[1].slice(0,5),['2026-10-01T17:00:00.000Z','01:02','Gol','Ñandúes','']);assert.equal(rows[1][7],'Ana');assert.deepEqual(rows[2].slice(2,5),['Time-out','Los "Halcones", Córdoba','Time-out']);});
test('CSV quotes commas, quotes and newlines, and neutralizes formulas',()=>{const rows=parseCSV(X.toCSV(sample()).slice(1));assert.equal(rows[3][6],'línea 1\nlínea 2 (leve) \\ nada');assert.equal(rows[1][8],`'=HYPERLINK("x")`);assert.equal(X.csvCell('+1'),"'+1");assert.equal(X.csvCell('-2'),"'-2");assert.equal(X.csvCell('@a'),"'@a");assert.equal(X.csvCell('plain'),'plain');});
test('CSV of a sheet without events is just the header',()=>{assert.equal(X.toCSV(match()),'﻿fecha_hora,tiempo_juego,evento,equipo,cronometro,detalle,nota,gol,pase,modo\r\n');});
test('event description matches the saved-sheet modal wording',()=>{const m=sample();assert.equal(X.describeEvent(m,m.events[0]),'Gol · Ñandúes · gol: Ana · pase: =HYPERLINK("x")');assert.equal(X.describeEvent(m,m.events[1]),'Time-out · Los "Halcones", Córdoba · Time-out');assert.equal(X.describeEvent(m,{type:'mystery'}),'mystery');});
test('PDF text escapes delimiters and maps to WinAnsi',()=>{assert.equal(X.pdfText('a(b)c\\'),'a\\(b\\)c\\\\');assert.equal(X.pdfText('Ñ—−€'),'\xd1\x97-\x80');assert.equal(X.pdfText('日本'),'??');});
test('PDF is well formed: header, valid xref offsets, trailer and Latin text',()=>{const bytes=X.toPDF(sample(),{rulesetLabel:'WFDF 2025–2028'});assert.ok(bytes instanceof Uint8Array);const pdf=latin1(bytes);assert.ok(pdf.startsWith('%PDF-1.4\n'));assert.ok(pdf.endsWith('%%EOF\n'));const xref=Number(/startxref\n(\d+)\n/.exec(pdf)[1]);assert.ok(pdf.slice(xref).startsWith('xref\n'));const entries=[...pdf.slice(xref).matchAll(/^(\d{10}) 00000 n $/gm)].map(m=>Number(m[1]));const size=Number(/\/Size (\d+)/.exec(pdf)[1]);assert.equal(entries.length,size-1);entries.forEach((offset,i)=>assert.ok(pdf.slice(offset).startsWith(`${i+1} 0 obj\n`),`object ${i+1}`));for(const m of pdf.matchAll(/<< \/Length (\d+) >>\nstream\n/g)){const start=m.index+m[0].length;assert.equal(pdf.slice(start+Number(m[1]),start+Number(m[1])+10),'\nendstream');}assert.ok(pdf.includes('(\xd1and\xfaes 2 \x97 1 Los "Halcones", C\xf3rdoba) Tj'));assert.ok(pdf.includes('l\xednea 2 \\(leve\\) \\\\ nada'));assert.ok(pdf.includes('WFDF 2025\x962028'));});
test('PDF paginates long sheets and numbers every page',()=>{const events=Array.from({length:150},(_,i)=>({type:'call',at:'2026-10-01T17:00:00.000Z',elapsed:i*10,team:i%2,label:'Falta'}));const pdf=latin1(X.toPDF(match(events)));const count=Number(/\/Type \/Pages \/Kids \[[^\]]*\] \/Count (\d+)/.exec(pdf)[1]);assert.ok(count>=3,`pages: ${count}`);assert.equal((pdf.match(/\/Type \/Page \//g)||[]).length,count);assert.ok(pdf.includes(`(P\xe1gina ${count} de ${count}) Tj`));for(const m of pdf.matchAll(/ (\d+) Td/g))assert.ok(Number(m[1])>=30);});
test('PDF of a sheet without events says so',()=>{assert.ok(latin1(X.toPDF(match())).includes('(Sin eventos) Tj'));});
