(() => {
  "use strict";
  const RULES_URL = "https://usaultimate.org/rules/";
  const KEY = "punto-por-punto-v2";
  const CHAPTERS = [
    ["inicio","01","Antes del pull","§§1–9","El punto, el saque y las decisiones previas."],
    ["disco","02","Disco en juego","§§10–14","Reinicios, límites, posesión, gol y turnover."],
    ["marca","03","Marca y pivote","§§15–19","Conteo, violaciones de marca, travels y picks."],
    ["seguridad","04","Contacto y espacio","§§20–21","Faltas, seguridad y derecho a ocupar el campo."],
    ["spirit","05","Spirit y variantes","§§22–23 · A–G","Observers, etiqueta y formatos especiales."]
  ];
  const S = (id,chapter,title,context,prompt,options,answer,hint,explain,source,visual) => ({id,chapter,title,context,prompt,options,answer,hint,explain,source,visual});
  const SCENARIOS = [
    S("basics","inicio","El disco no se corre","Tu equipo recibe y busca llegar a la end zone rival.","¿Cómo avanza el disco?",["Mediante un pase a otra persona","Corriendo con el disco","Pateándolo"],0,"Pensá qué hace avanzar el disco y qué no puede hacer quien lo sostiene.","En Ultimate estándar juegan siete por lado. El disco avanza mediante pases; quien tiene posesión no puede correr con él. El juego es sin contacto y autoarbitrado.","USAU §§1–2","pass"),
    S("simultaneous-catch","inicio","Captura simultánea","Una atacante y una defensora atrapan el mismo disco al mismo tiempo.","¿Quién conserva la posesión?",["La atacante","La defensora","Se repite el pull"],0,"La definición trata expresamente el empate entre ataque y defensa.","Si ataque y defensa capturan simultáneamente, el ataque conserva la posesión. Esa atacante pasa a ser la persona lanzadora.","USAU §3.I.6","simultaneous"),
    S("sideline","inicio","La línea no cuenta","Una receptora atrapa el disco, pero su primer apoyo toca la línea lateral.","¿Ese apoyo está dentro?",["No: la línea perimetral es fuera","Sí: la línea forma parte del campo","Solo si toca un cono"],0,"La cancha es la superficie interior, no las líneas que la delimitan.","Las líneas perimetrales no forman parte del campo. Para estar dentro, todos los puntos de contacto con el suelo deben estar completamente dentro de esas líneas.","USAU §§4, 11","sideline"),
    S("game-and-timeouts","inicio","Formato estándar","El evento anuncia que usa la estructura estándar de USAU.","¿Cuál es el game total y cuántos timeouts de equipo hay por mitad?",["15 goles y 2 timeouts","11 goles y 1 timeout","21 goles y 3 timeouts"],0,"La organización puede anunciar cambios, pero existe una base estándar.","El game total estándar es 15. Cada equipo cuenta con dos timeouts de equipo por mitad, salvo ajustes anunciados para el evento.","USAU §§6–7","score"),
    S("substitution-pull","inicio","Cambio y saque","Tu equipo acaba de anotar y todavía no señaló que está listo.","¿Qué ocurre ahora?",["Puede sustituir; quien anotó hace el pull","Solo puede sustituir después del pull","El receptor vuelve a lanzar"],0,"Separá las sustituciones del orden de quién inicia el punto.","Las sustituciones normales se hacen después de un gol y antes de que el equipo que sustituye indique que está listo. Los equipos cambian de dirección y el equipo que anotó hace el pull.","USAU §§8–9","pull"),
    S("live-restart","disco","Puesta en juego","Tras un turnover, el disco vivo debe jugarse desde un punto distinto de donde se ganó la posesión.","¿Qué debe hacer quien lanza antes de pasar?",["Fijar el pivote y tocar el disco al suelo","Esperar un silbato","Lanzar desde cualquier lugar"],0,"Si el disco está vivo pero se juega desde otro punto, hay una puesta en juego específica.","Quien lanza establece el pivote en el lugar apropiado y toca el disco con el suelo antes de intentar un pase. Ese procedimiento no requiere una detención previa.","USAU §10.C","restart"),
    S("pass-out","disco","Pase fuera de límites","Un pase incompleto toca el área fuera de la línea perimetral.","¿Qué ocurre?",["Turnover; se reinicia cerca de donde salió","El ataque conserva desde el fondo","Se repite el pase"],0,"Combiná la regla de pase incompleto con el lugar de reinicio de un disco out.","Un pase incompleto produce turnover. Cuando el disco queda fuera, la nueva ofensiva lo lleva al punto de la zona central más cercano a la salida y lo pone en juego correctamente.","USAU §§11, 14","out"),
    S("own-endzone","disco","Turnover en end zone propia","Tu equipo gana la posesión dentro de la end zone que defiende.","¿Qué puede hacer quien recoge el disco?",["Pivotar allí o llevarlo directo a la goal line","Anotar automáticamente","Lanzar sin fijar pivote"],0,"La regla ofrece dos caminos concretos en la end zone propia.","La nueva ofensiva puede establecer el pivote en el lugar del disco o llevarlo directamente al punto más cercano de la goal line. Una pausa o amague antes de avanzar elige la primera opción.","USAU §12.A","own-zone"),
    S("attacked-endzone","disco","No todo control es gol","Una jugadora controla el disco en la end zone que ataca, pero no completó un gol válido.","¿Dónde debe ponerlo en juego?",["En la goal line más cercana","En el fondo de la end zone","En el brick mark"],0,"Tener el disco en la end zone de ataque no basta por sí solo.","Si se gana o conserva posesión en la end zone de ataque sin gol, la persona lanzadora lleva el disco directamente a la goal line más cercana y juega desde allí.","USAU §12.B","attack-zone"),
    S("goal-catch","disco","Gol controlado","Una receptora atrapa un pase legal dentro de la end zone que ataca.","¿Qué confirma el gol?",["Controlar el disco hasta completar el contacto con el suelo","Tocarlo antes de caer","Que el disco cruce la goal line"],0,"Importan la posesión y el primer contacto con el suelo asociado a la captura.","Es gol cuando una persona dentro del campo atrapa un pase legal en la end zone de ataque y mantiene posesión durante todo el contacto con el suelo relacionado con la captura.","USAU §13.A","goal"),
    S("stall-ten","marca","El primer «ten»","La primera sílaba de «ten» suena y el disco sigue en manos de quien lanza.","¿Qué decisión corresponde?",["Turnover por stall","La cuenta vuelve a uno","El pase sigue siendo legal"],0,"La regla mira si el disco salió antes de la primera pronunciación de «ten».","Si el disco no fue soltado al comenzar «ten», hay turnover por stall. Si ya fue lanzado, primero se determina el resultado del pase.","USAU §15.D","stall"),
    S("marking-violation","marca","Espacio de disco","La lanzadora llama «disc space»: la marca invadió el espacio reglamentario.","¿Se detiene el juego?",["No; se corrige y el conteo baja uno","Sí; siempre hay check","Sí; la defensa gana el disco"],0,"Una infracción de marca no sigue el mismo procedimiento que una falta que detiene la jugada.","La llamada la hace la persona lanzadora. El juego no se detiene: la marca corrige su posición y el conteo sigue desde el último número pronunciado menos uno.","USAU §16.B–C","mark"),
    S("continuation","marca","El disco está en el aire","Se llama una infracción cuando el disco ya está en vuelo.","¿Qué pasa primero?",["Se determina el resultado del pase","Vuelve de inmediato al lanzador","El punto termina"],0,"La continuación evita borrar una acción que todavía no terminó.","Cuando una llamada ocurre durante el lanzamiento o con el disco en el aire, primero se determina el resultado del pase. Luego se aplica la resolución correspondiente.","USAU §17.C","continuation"),
    S("travel","marca","Pivote desplazado","La marca señala un travel antes de que se intente un pase.","Si no se disputa, ¿qué debe ocurrir?",["Volver al punto indicado y tocar el disco al suelo","Detener el juego y dar turnover","Elegir cualquier pivote nuevo"],0,"Sin pase intentado, el juego sigue mientras se corrige el punto.","Sin pase intentado, la jugada no se detiene. La defensa indica el lugar; quien lanza vuelve allí, establece el pivote y toca el disco al suelo antes de pasar.","USAU §18.F.2","pivot"),
    S("pick","marca","Corte bloqueado","Una defensora que cubre a una atacante debe esquivar a otra persona y pierde su posición relativa.","¿Quién puede llamar «pick» y cuándo?",["La defensora obstruida, inmediatamente","Cualquier compañera al final","Solo quien tiene el disco"],0,"La llamada pertenece a quien perdió su cobertura por la obstrucción.","Solo la persona defensora obstruida puede llamar «pick», en voz alta e inmediatamente. Después se aplica continuación y, si hay detención, recupera la posición relativa perdida.","USAU §19.A–C","pick"),
    S("dangerous-play","seguridad","Riesgo antes que resultado","Una persona corre sin mirar hacia un grupo y causa una colisión significativa mientras disputan el disco.","¿Qué debe priorizar el juego?",["La seguridad; puede ser dangerous play","Seguir porque el disco está en el aire","Dar posesión a quien llegó primero"],0,"La conducta peligrosa no queda justificada por estar cerca del disco.","Una conducta temeraria o con riesgo significativo de lesión puede llamarse dangerous play. La seguridad se atiende antes de resolver el resultado deportivo.","USAU §20.B","danger"),
    S("receiving-foul","seguridad","Contacto que afecta la recepción","Con el disco en vuelo, una defensora hace contacto no incidental y afecta el intento de una rival.","¿Qué describe mejor la acción?",["Receiving foul","Turnover automático","Marking violation"],0,"Buscá la categoría de contacto que afecta una jugada sobre un disco en vuelo.","El contacto no incidental que afecta el intento de una oponente de jugar el disco en vuelo puede ser una receiving foul. El contacto incidental que no afecta la jugada no es, por sí solo, una falta.","USAU §§3, 20.E","contact"),
    S("who-calls-foul","seguridad","Llamar la falta","Una jugadora recibe contacto no incidental y lo percibe con certeza.","¿Quién debe llamar «foul»?",["La persona que recibió la falta","Cualquier persona cercana","Solo el capitán"],0,"Las llamadas las hace quien fue afectada y percibió la infracción.","La persona que recibió el contacto puede llamar «foul» y debe hacerlo en voz alta inmediatamente después de que ocurra.","USAU §§17.A, 20.C","foul"),
    S("jump-landing","seguridad","Lugar de aterrizaje","Una receptora salta. Al despegar, otra persona ya ocupa tanto el lugar de aterrizaje como el camino directo.","¿Puede aterrizar allí ignorando ese espacio?",["No; el lugar y el camino ya estaban ocupados","Sí; saltar da prioridad absoluta","Sí, si atrapa con dos manos"],0,"El derecho a otro lugar de aterrizaje depende de cómo estaba el espacio al despegar.","Quien salta tiene derecho a aterrizar en el punto de despegue. Otro lugar solo está disponible si el destino y el trayecto directo estaban libres al despegar, y siempre hay que evitar el contacto.","USAU §21.B","landing"),
    S("positioning","seguridad","Impedir el pivote","Una defensora se mueve para impedir que el ataque tome el disco o establezca un pivote.","¿Está permitido?",["No; no puede obstruir esas acciones","Sí; puede bloquear cualquier lugar","Sí, si no empezó el stall"],0,"Hay una restricción específica sobre tomar posesión y establecer el pivote.","La defensa no puede moverse de forma que obstruya al ataque para tomar posesión del disco o establecer un pivote. Tampoco puede usar brazos o piernas extendidos para bloquear.","USAU §21.C–D","block"),
    S("observer","spirit","Resolver una disputa","En un partido con observers, las personas directamente involucradas no logran resolver una disputa.","¿Qué puede ocurrir?",["Una involucrada puede pedir resolución al observer","El coach decide","Gana quien gritó primero"],0,"Los observers tienen funciones delimitadas; no sustituyen el diálogo en todos los casos.","Una persona directamente involucrada puede solicitar la resolución de un observer. También puede intervenir si la disputa no se resuelve con rapidez; después se reinicia con check.","USAU §22.B.2","observer"),
    S("novice-etiquette","spirit","Aprender en cancha","Una persona nueva infringe una regla por desconocimiento sincero.","¿Qué recomienda la etiqueta?",["Detenerse y explicarle la infracción","Dejar que siga","Discutirlo al final"],0,"La regla contempla expresamente a quien aprende de buena fe.","Cuando una persona novata comete una infracción por desconocimiento sincero, la práctica recomendada es detenerse y explicar lo ocurrido para continuar con claridad.","USAU §23.D","talk"),
    S("appendix-field","spirit","Mapa de cancha","El equipo consulta el anexo A antes de entrenar.","¿Qué muestra?",["Zonas y líneas del campo","Señales de observers","Ratios mixtos"],0,"Es el anexo de orientación física del terreno.","El anexo A presenta el diagrama de cancha: zonas, líneas perimetrales y goal lines para ubicar reinicios y jugadas dentro o fuera.","USAU Appendix A","field"),
    S("appendix-mixed","spirit","Formato mixto","Un torneo mixto usa la regla base sin una adaptación adicional anunciada.","¿Cuál es la proporción por defecto?",["4/3","5/2","6/1"],0,"Siete lugares se distribuyen en grupos de cuatro y tres.","La proporción predeterminada en división mixta es 4/3. El organizador puede anunciar un método distinto; siempre hay que revisar qué regla aplica al evento.","USAU Appendix B1.A","teams"),
    S("appendix-map","spirit","Buscar una variante","Querés ubicar una adaptación específica antes de jugar otra modalidad.","¿Qué lista es correcta?",["C: conducta · D: señales · E: youth · F: beach · G: 4’s","C: beach · D: mixto · E: observers · F: youth · G: señales","C: señales · D: 4’s · E: beach · F: conducta · G: mixto"],0,"Los anexos agrupan sistemas y adaptaciones, no reemplazan por defecto el formato estándar.","Los anexos cubren conducta, señales manuales, youth, Beach Ultimate y Ultimate 4’s. Las reglas del evento indican si alguna variante está vigente.","USAU Appendices C–G","variants")
  ];
  const FLOW = [
    ["El pull inicia el punto", "El equipo que anotó lanzó el pull. ¿Qué empieza con ese lanzamiento?", ["Un punto nuevo","Un timeout automático","Un turnover"],0,"El pull inicia cada punto.","USAU §9"],
    ["El pull cruza la línea", "El pull cae completamente fuera de la línea perimetral sin ser tocado. ¿Qué opción tiene el equipo receptor?", ["Elegir el brick o jugar desde el punto aplicable","Repetir siempre el pull","Dar el disco al equipo que lanzó"],0,"Un pull fuera no obliga por sí mismo a repetirlo.","USAU §§9, 11"],
    ["Poner el disco en juego", "Elegida la puesta en juego, la persona lanzadora va al lugar apropiado. ¿Qué sigue?", ["Fija pivote y pone el disco en juego","Corre hasta el centro con el disco","Espera que un observer silbe"],0,"El check solo se usa cuando la regla indica una reanudación tras detención.","USAU §10"],
    ["Primer pase", "El disco ya está vivo. Una lanzadora pivotea y pasa a una compañera dentro de la cancha. ¿Qué decide la continuación?", ["Si la receptora completa la posesión","La cantidad de gritos desde la línea","Si el disco cruzó media cancha"],0,"Un pase se resuelve por su resultado: completo, incompleto, interceptado, etc.","USAU §§3, 14"],
    ["Pase completo", "La receptora controla el disco dentro del campo. ¿Quién tiene la posesión ahora?", ["El ataque, con esa receptora como lanzadora","La defensa por haber tocado el aire","Nadie hasta un silbato"],0,"La posesión se transfiere con una recepción completa.","USAU §3"],
    ["Llamada de marca", "La marca hace fast count. La lanzadora llama la infracción antes de lanzar. ¿Se detiene el juego?", ["No; se corrige la marca y el conteo baja uno","Sí; la defensa recibe el disco","Sí; se borra el punto"],0,"Las infracciones de marca tienen procedimiento propio.","USAU §16"],
    ["El disco viaja", "Luego hay un pase legal a la end zone de ataque. La receptora lo controla mientras completa el contacto con el suelo. ¿Resultado?", ["Gol","Turnover","Pick"],0,"El control debe mantenerse durante el contacto con el suelo asociado a la captura.","USAU §13"],
    ["Después del gol", "El gol fue válido. ¿Qué orden corresponde para el punto siguiente?", ["Cambio de dirección; quien anotó hace el pull","El receptor anterior hace el pull","El juego sigue sin pull"],0,"Después de un gol, se cambia dirección y se inicia otro punto.","USAU §§8–9, 13"]
  ];
  const app = document.getElementById("appMain"), note = document.getElementById("storageNote"), nav = [...document.querySelectorAll("[data-view]")];
  const $ = (q, el=document) => el.querySelector(q);
  const esc = (v) => String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const fresh = () => ({v:2, duration:"medium", profile:{best:0,seen:[],right:0,wrong:0,finished:0,review:[]},run:null,flow:null});
  let state; try { state={...fresh(),...JSON.parse(localStorage.getItem(KEY)||"null")}; state.profile={...fresh().profile,...state.profile}; } catch { state=fresh(); }
  const save = () => { try { localStorage.setItem(KEY,JSON.stringify(state)); note.hidden=true; } catch { note.textContent="Tu progreso queda en esta pestaña: el navegador no permitió guardarlo."; note.hidden=false; } };
  const get = id => SCENARIOS.find(x=>x.id===id), ch = id => CHAPTERS.find(x=>x[0]===id), alive = () => state.run && !state.run.done;
  const durationIds = (d) => { const core=["basics","simultaneous-catch","substitution-pull","live-restart","pass-out","goal-catch","stall-ten","marking-violation","continuation","travel","pick","dangerous-play","receiving-foul","observer","novice-etiquette"]; return d==="short"?core.slice(0,8):d==="medium"?core:SCENARIOS.map(x=>x.id); };
  const hearts = n => `<span class="lives" aria-label="${n} vidas de 3">${[1,2,3].map(i=>`<i class="heart${i>n?" is-empty":""}">◆</i>`).join("")}<b>${n}/3</b></span>`;
  function scene(s) {
    const map={pass:["M95 162 Q240 40 435 115","PASE",""],simultaneous:["M280 90 Q302 70 321 92","CAPTURA","SIMULTÁNEA"],sideline:["M308 148 Q420 46 536 69","OUT","PIE EN LÍNEA"],score:["M110 110 L465 110","15","2 T/O"],pull:["M70 80 Q280 200 505 95","PULL",""],restart:["M215 155 L215 129","TOQUE","PIVOTE"],out:["M258 125 Q445 20 545 80","OUT","TURNOVER"],"own-zone":["M80 120 L142 120","OPCIONES","GOAL LINE"],"attack-zone":["M500 120 L445 120","NO GOL","GOAL LINE"],goal:["M350 125 Q470 80 518 106","GOL","CONTROL"],stall:["M245 145 L310 145","STALL","10"],mark:["M260 132 Q295 105 330 130","MARCA","ESPACIO"],continuation:["M170 160 Q310 40 442 104","LLAMADA","DISCO EN AIRE"],pivot:["M254 147 A32 32 0 0 1 315 145","TRAVEL","VOLVER"],pick:["M205 120 L310 120","PICK","OBSTRUCCIÓN"],danger:["M290 150 Q330 80 365 115","RIESGO","EVITAR"],contact:["M285 135 L332 110","CONTACTO",""],foul:["M280 130 L332 130","FOUL",""],landing:["M280 150 Q310 45 345 148","SALTO","ESPACIO"],block:["M243 150 L285 150","PIVOTE","NO BLOQUEAR"],observer:["M260 110 L322 110","RESOLVER","OBSERVER"],talk:["M245 125 Q290 80 340 126","EXPLICAR",""],field:["M85 50 L500 50","CANCHA",""],teams:["M160 135 L420 135","4 / 3",""],variants:["M155 75 L430 178","A–G",""]};
    const [p,a,b]=map[s.visual]||map.pass;
    const people=[[120,162,"O"],[190,89,"O"],[254,146,"O"],[342,92,"O"],[435,143,"O"],[486,72,"O"],[505,168,"O"],[145,115,"D"],[220,173,"D"],[300,105,"D"],[375,157,"D"],[430,65,"D"]].map(([x,y,t])=>`<g class="token token-${t}"><circle cx="${x}" cy="${y}" r="10"/><text x="${x}" y="${y+3}">${t}</text></g>`).join("");
    return `<svg class="tactic" viewBox="0 0 580 235" role="img" aria-label="Diagrama: ${esc(s.title)}"><defs><pattern id="hatch-${s.id}" width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><line x1="0" y1="0" x2="0" y2="7" stroke="rgba(255,250,226,.25)" stroke-width="1"/></pattern></defs><rect class="court" x="20" y="18" width="540" height="195"/><rect class="zone" x="20" y="18" width="62" height="195" fill="url(#hatch-${s.id})"/><rect class="zone" x="498" y="18" width="62" height="195" fill="url(#hatch-${s.id})"/><path class="courtline" d="M20 18H560V213H20zM82 18V213M498 18V213M290 18V213"/>${people}<path class="route" d="${p}"/><circle class="disc" cx="435" cy="115" r="7"/><g class="callout"><text x="290" y="30">${a}</text><text x="290" y="205">${b}</text></g></svg>`;
  }
  const header = (label,extra="") => `<div class="mast"><div><p class="kicker">PUNTO POR PUNTO / ${label}</p><h1 tabindex="-1">${extra}</h1></div></div>`;
  function setView(v,focus=true){ nav.forEach(b=>{const on=b.dataset.view===v;b.classList.toggle("is-current",on);on?b.setAttribute("aria-current","page"):b.removeAttribute("aria-current")}); if(v==="home") home(); if(v==="game") game(); if(v==="flow") flow(); if(v==="progress") progress(); if(v==="rules") rules(); if(focus)requestAnimationFrame(()=>$("h1",app)?.focus({preventScroll:true})); save(); }
  function home(){ const run=alive(); app.innerHTML=`<section class="launch"><div class="launch-copy"><p class="issue">EDICIÓN DE JUEGO · USAU 2026–2027</p><h1 tabindex="-1">Reglas que se ven <em>en cancha.</em></h1><p class="lede">Leé una situación, mirá el diagrama preciso y elegí. Las referencias oficiales quedan al lado de cada decisión.</p><div class="duration" role="radiogroup" aria-label="Duración de la partida"><span>Duración</span>${[["short","Corto","8 jugadas"],["medium","Medio","15 jugadas"],["long","Largo","25 jugadas"]].map(([id,n,d])=>`<button type="button" class="duration-choice ${state.duration===id?"is-selected":""}" data-duration="${id}" role="radio" aria-checked="${state.duration===id}"><b>${n}</b><small>${d}</small></button>`).join("")}</div><div class="launch-actions"><button class="action action-main" data-action="${run?"resume":"start"}">${run?"Continuar partida":"Jugar ahora"}</button><button class="action action-line" data-view="flow">Abrir DIAGRAMA DE JUEGO</button></div></div><figure class="atlas"><img src="assets/atlas-tactico-v2.png" alt="Cancha de Ultimate serigrafiada con rutas de pase y jugadoras."><figcaption>ATAQUE / DEFENSA / RUTAS / DECISIONES</figcaption></figure></section><section class="entry-grid" aria-label="Capítulos">${CHAPTERS.map(([id,n,t,r,d])=>`<article class="chapter-entry"><span>${n} · ${r}</span><h2>${t}</h2><p>${d}</p><button class="text-action" data-action="chapter" data-chapter="${id}">Practicar este bloque</button></article>`).join("")}</section><aside class="method"><b>Cómo leer esta guía</b><p>Paráfrasis pedagógicas en español, diagramas propios y enlaces a las reglas USA Ultimate. Si el evento anuncia modificaciones, esas modificaciones mandan.</p></aside>`; }
  function start(chapter="all"){ const ids=chapter==="all"?durationIds(state.duration):SCENARIOS.filter(x=>x.chapter===chapter).map(x=>x.id); state.run={ids,index:0,lives:3,score:0,chosen:null,feedback:null,done:false,chapter}; setView("game"); }
  function game(){const r=state.run;if(!r){setView("home",false);return;}const s=get(r.ids[r.index]); if(!s){r.done=true;return finish();} const feedback=r.feedback; const opts=s.options.map((o,i)=>`<label class="choice ${feedback&&i===s.answer?"correct":""} ${feedback&&!feedback.ok&&i===feedback.pick?"wrong":""}"><input type="radio" name="answer" value="${i}" ${r.chosen===i?"checked":""} ${feedback?"disabled":""}><i>${feedback?(i===s.answer?"✓":i===feedback.pick?"×":String.fromCharCode(65+i)):String.fromCharCode(65+i)}</i><span>${esc(o)}</span></label>`).join(""); app.innerHTML=`<section class="play"><div class="scoreboard"><span>JUGADA ${r.index+1}/${r.ids.length}</span><div class="meter"><i style="width:${Math.round(r.index/r.ids.length*100)}%"></i></div><strong>${r.score} PTS</strong>${hearts(r.lives)}</div>${header(s.source,s.title)}<div class="play-grid"><figure class="diagram"><div class="diagram-head"><span>LECTURA TÁCTICA</span><b>${esc(s.visual.replace("-"," "))}</b></div>${scene(s)}<figcaption><span class="dot offense"></span> ataque <span class="dot defense"></span> defensa <span class="dot route-dot"></span> acción relevante</figcaption></figure><section class="decision"><p class="situation">${esc(s.context)}</p><form id="answerForm"><fieldset ${feedback?"disabled":""}><legend>${esc(s.prompt)}</legend><div class="choices">${opts}</div></fieldset><div class="controls"><button class="action action-main" type="submit" ${r.chosen===null||feedback?"disabled":""}>Confirmar decisión</button><button class="text-action" type="button" data-action="hint">Ver pista</button></div><p id="hint" class="hint" hidden>${esc(s.hint)}</p></form>${feedback?`<aside class="feedback ${feedback.ok?"is-good":"is-bad"}" role="status"><b>${feedback.ok?"Lectura correcta.":"No era ese recorrido."}</b><p>${feedback.ok?"+100 puntos. ":"La respuesta correcta era: “"+esc(s.options[s.answer])+"”. "}${esc(s.explain)}</p><a href="${RULES_URL}" target="_blank" rel="noreferrer">${esc(s.source)} · texto oficial</a><button class="action action-main" data-action="next">${r.done?"Ver resultado":"Siguiente jugada"}</button></aside>`:""}</section></div></section>`; }
  function answer(){const r=state.run,s=get(r.ids[r.index]);if(!r||r.feedback||r.chosen===null)return;const ok=r.chosen===s.answer;r.feedback={ok,pick:r.chosen};state.profile.seen=[...new Set([...state.profile.seen,s.id])]; if(ok){r.score+=100;state.profile.right++;state.profile.review=state.profile.review.filter(x=>x!==s.id);}else{r.lives--;state.profile.wrong++;state.profile.review=[...new Set([...state.profile.review,s.id])];}state.profile.best=Math.max(state.profile.best,r.score);if(r.lives===0||r.index===r.ids.length-1)r.done=true;save();game();}
  function next(){const r=state.run;if(r.done)return finish();r.index++;r.chosen=null;r.feedback=null;game();}
  function finish(){const r=state.run;state.profile.finished++;app.innerHTML=`<section class="result">${header(r.lives?"RECORRIDO COMPLETO":"TRES VIDAS",r.lives?"Terminaste el recorrido.":"La cancha te pide repaso.")}<div class="result-grid"><p>Sumaste <strong>${r.score} puntos</strong> y terminaste con ${r.lives} de 3 vidas. Las reglas que costaron quedan marcadas para volver a intentarlas.</p><div>${hearts(r.lives)}<p>${state.profile.review.length} reglas en repaso</p></div></div><div class="launch-actions"><button class="action action-main" data-action="restart">Jugar otra vez</button><button class="action action-line" data-view="flow">DIAGRAMA DE JUEGO</button></div></section>`;save();}
  function flow(){const f=state.flow||{index:0,lives:3,score:0,chosen:null,feedback:null,done:false};state.flow=f;if(f.done)return flowFinish();const step=FLOW[f.index];const nodes=FLOW.map((x,i)=>`<li class="flow-node ${i<f.index?"done":i===f.index?"current":"locked"}"><b>${String(i+1).padStart(2,"0")}</b><span>${esc(x[0])}</span></li>`).join("");app.innerHTML=`<section class="flow-mode">${header("DIAGRAMA DE JUEGO","Elegí el recorrido que desbloquea la cancha.")}<p class="lede">No es un mapa pasivo: cada decisión correcta abre la siguiente. Tenés tres vidas para llegar al final.</p><div class="flow-status"><span>PASO ${f.index+1}/${FLOW.length}</span><span>${f.score} PTS</span>${hearts(f.lives)}</div><div class="flow-layout"><ol class="flow-map">${nodes}</ol><section class="flow-question"><p class="rule-tag">${step[5]}</p><h2>${esc(step[0])}</h2><p>${esc(step[1])}</p><div class="flow-answers">${step[2].map((x,i)=>`<button class="flow-answer ${f.feedback&&i===step[3]?"correct":""} ${f.feedback&&!f.feedback.ok&&i===f.feedback.pick?"wrong":""}" data-flow-answer="${i}" ${f.feedback?"disabled":""}>${String.fromCharCode(65+i)} <span>${esc(x)}</span></button>`).join("")}</div>${f.feedback?`<aside class="feedback ${f.feedback.ok?"is-good":"is-bad"}" role="status"><b>${f.feedback.ok?"Nodo desbloqueado.":"Ese camino no aplica."}</b><p>${esc(step[4])}</p><button class="action action-main" data-action="flow-next">${f.done?"Ver resultado":"Seguir el flujo"}</button></aside>`:""}</section></div><p class="flow-source">Flujo de aprendizaje basado en ${RULES_URL}</p></section>`;}
  function flowAnswer(pick){const f=state.flow,step=FLOW[f.index];if(!f||f.feedback)return;const ok=pick===step[3];f.feedback={ok,pick};if(ok){f.score+=100;}else f.lives--;if(f.lives===0||f.index===FLOW.length-1)f.done=true;save();flow();}
  function flowNext(){const f=state.flow;if(f.done)return flowFinish();f.index++;f.feedback=null;flow();}
  function flowFinish(){const f=state.flow;app.innerHTML=`<section class="result">${header("DIAGRAMA DE JUEGO",f.lives?"Flujo completo desbloqueado.":"El flujo se detuvo.")}<div class="result-grid"><p>${f.lives?"Llegaste desde el pull hasta el siguiente punto con el recorrido correcto.":"Las tres vidas se agotaron. Repasá los nodos y volvé a intentarlo."}</p><div>${hearts(f.lives)}<p>${f.score} puntos</p></div></div><div class="launch-actions"><button class="action action-main" data-action="flow-restart">Reintentar diagrama</button><button class="action action-line" data-view="rules">Consultar reglas</button></div></section>`;}
  function progress(){const p=state.profile,total=SCENARIOS.length,accuracy=p.right+p.wrong?Math.round(p.right/(p.right+p.wrong)*100):0;app.innerHTML=`<section class="progress-page">${header("REGISTRO DE ENTRENAMIENTO","Lo visto, lo pendiente.")}<div class="ledger"><div><b>${p.best}</b><span>mejor puntaje</span></div><div><b>${p.seen.length}/${total}</b><span>situaciones vistas</span></div><div><b>${accuracy}%</b><span>acierto registrado</span></div><div><b>${p.review.length}</b><span>para repasar</span></div></div><div class="progress-list">${CHAPTERS.map(([id,n,t])=>{const xs=SCENARIOS.filter(x=>x.chapter===id),d=xs.filter(x=>p.seen.includes(x.id)).length;return `<div><span>${n}</span><b>${t}</b><i><em style="width:${d/xs.length*100}%"></em></i><small>${d}/${xs.length}</small></div>`}).join("")}</div><p class="method">El progreso se guarda solo en este navegador. No se crea cuenta ni se envían datos.</p></section>`;}
  const rulesData=[["§1","Principios", "Siete contra siete, sin contacto: el disco avanza con pases y una recepción incompleta cambia la posesión."],["§2","Spirit of the Game","Cada persona comparte la responsabilidad de jugar limpio, resolver desacuerdos y aplicar las reglas."],["§3","Definiciones","Aclara posesión, pivote, lanzador, marca y los estados del disco: en juego, vivo o muerto."],["§4–5","Cancha y equipamiento","Las líneas perimetrales están fuera. El equipamiento y el calzado deben ser seguros."],["§6–9","Partido, timeouts, cambios y pull","Estructura del encuentro, pausas, sustituciones y cómo se inicia cada punto."],["§10–14","Disco, límites, end zones y turnover","Puesta en juego, dentro/fuera, posesión en end zone, gol y cambios de posesión."],["§15–16","Stall y marca","Conteo 1–10 e infracciones de marca: fast count, double team, disc space, straddle, wrapping y visión."],["§17","Llamadas y resolución","Una llamada debe ser inmediata y percibida con certeza. Con disco en vuelo se aplica la regla de continuación."],["§18–19","Travel y pick","Pivote correcto, corrección del travel y obstrucción de una cobertura defensiva."],["§20–21","Faltas, seguridad y espacio","Contacto no incidental, dangerous play, derecho a la posición y aterrizajes."],["§22–23","Observers y etiqueta","Funciones de observers y prácticas de diálogo, respeto y enseñanza en cancha."],["A–G","Anexos","Cancha, mixto, conducta, señales, youth, beach y Ultimate 4’s."]];
  function rules(){app.innerHTML=`<section class="rules-page">${header("REFERENCIA · USAU 2026–2027","Reglas, sin traducción automática.")}<p class="lede">Esta es una guía interpretativa en español. Conservamos términos de uso habitual —pull, check, stall, pivot, mark— y los explicamos en contexto. Para una decisión oficial, consultá el texto de USA Ultimate y las reglas del evento.</p><label class="search"><span>Buscar sección, concepto o término</span><input id="ruleSearch" type="search" placeholder="Ej.: pull, fuera, pivot, foul"></label><div id="ruleList" class="rule-list">${rulesData.map(([r,t,d])=>`<article data-search="${esc((r+" "+t+" "+d).toLowerCase())}"><span>${r}</span><div><h2>${t}</h2><p>${d}</p><a href="${RULES_URL}" target="_blank" rel="noreferrer">Abrir regla oficial</a></div></article>`).join("")}</div><p class="method">Glosario breve: <b>pull</b>, saque que inicia el punto; <b>check</b>, toque que reanuda tras una detención; <b>stall</b>, conteo defensivo; <b>pivot</b>, punto de apoyo; <b>mark</b>, defensa directa de quien lanza.</p></section>`;}
  document.addEventListener("click",e=>{const v=e.target.closest("[data-view]");if(v)return setView(v.dataset.view);const a=e.target.closest("[data-action]");if(a){const x=a.dataset.action;if(x==="start")start();if(x==="resume")setView("game");if(x==="chapter")start(a.dataset.chapter);if(x==="next")next();if(x==="restart")start(state.run?.chapter||"all");if(x==="hint"){const h=$("#hint");h.hidden=!h.hidden;}if(x==="flow-next")flowNext();if(x==="flow-restart"){state.flow={index:0,lives:3,score:0,chosen:null,feedback:null,done:false};flow();}}const d=e.target.closest("[data-duration]");if(d){state.duration=d.dataset.duration;save();home();}const f=e.target.closest("[data-flow-answer]");if(f)flowAnswer(Number(f.dataset.flowAnswer));});
  document.addEventListener("change",e=>{if(e.target.name==="answer"&&alive()&&!state.run.feedback){state.run.chosen=Number(e.target.value);const b=$("#answerForm button[type=submit]");if(b)b.disabled=false;save();}});
  document.addEventListener("submit",e=>{if(e.target.id==="answerForm"){e.preventDefault();answer();}});
  document.addEventListener("input",e=>{if(e.target.id==="ruleSearch"){const q=e.target.value.toLowerCase().trim();document.querySelectorAll("#ruleList article").forEach(x=>x.hidden=q&&!x.dataset.search.includes(q));}});
  if(alive())setView("game",false);else home();
})();
